// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH5BCeL2DsfWbFPnaVacEl2IdwWmOZg64',
    appId: '1:352001320076:web:516c33f856675dd235c7a9',
    messagingSenderId: '352001320076',
    projectId: 'notif-firebase-36112',
    authDomain: 'notif-firebase-36112.firebaseapp.com',
    storageBucket: 'notif-firebase-36112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-Yb-6kNZN9G1yKzm99SRy2OjuC9GqsI',
    appId: '1:352001320076:android:fb48b6d17f55075735c7a9',
    messagingSenderId: '352001320076',
    projectId: 'notif-firebase-36112',
    storageBucket: 'notif-firebase-36112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3W6SB4Ya4cOyZTRsPc2dZXCvEIf_4dRU',
    appId: '1:352001320076:ios:1fff459c78372aba35c7a9',
    messagingSenderId: '352001320076',
    projectId: 'notif-firebase-36112',
    storageBucket: 'notif-firebase-36112.firebasestorage.app',
    iosBundleId: 'com.example.notifFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3W6SB4Ya4cOyZTRsPc2dZXCvEIf_4dRU',
    appId: '1:352001320076:ios:1fff459c78372aba35c7a9',
    messagingSenderId: '352001320076',
    projectId: 'notif-firebase-36112',
    storageBucket: 'notif-firebase-36112.firebasestorage.app',
    iosBundleId: 'com.example.notifFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH5BCeL2DsfWbFPnaVacEl2IdwWmOZg64',
    appId: '1:352001320076:web:b186a64a31b8f2aa35c7a9',
    messagingSenderId: '352001320076',
    projectId: 'notif-firebase-36112',
    authDomain: 'notif-firebase-36112.firebaseapp.com',
    storageBucket: 'notif-firebase-36112.firebasestorage.app',
  );
}
